/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package directorios;

import java.io.File;
import negocio.Navegador;
import java.util.ArrayList;
import bd.Archivo;
import javax.swing.JOptionPane;

/**
 *
 * @author profesor
 */
public class Directorios extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Directorios() {
        initComponents();
        setLocationRelativeTo(null);
        jComboBoxDirectorios.removeAllItems();

        Navegador n = new Navegador();
        Archivo archivo = n.crearArchivo(new File(".").getAbsolutePath());
        
// si no tengo crear archivo haria falta esto.
//        File f = new File ("/home/profesor/NetBeansProjects/JavaApplication1");
//        Archivo archivoTemp = new Archivo(f.getName(),true,"","");
        
        jComboBoxDirectorios.addItem(archivo);
        labelActualDir.setText(archivo.getPath());
    }
    
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButtonDirectorios = new javax.swing.JButton();
    labelActualDir = new javax.swing.JLabel();
    jComboBoxDirectorios = new javax.swing.JComboBox();
    jScrollPane1 = new javax.swing.JScrollPane();
    subdirectorios = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jButtonDirectorios.setText("Sacar Directorios");
    jButtonDirectorios.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonDirectoriosActionPerformed(evt);
      }
    });

    jComboBoxDirectorios.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "./" }));

    subdirectorios.setColumns(20);
    subdirectorios.setRows(5);
    jScrollPane1.setViewportView(subdirectorios);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(102, 102, 102)
            .addComponent(jButtonDirectorios))
          .addGroup(layout.createSequentialGroup()
            .addGap(64, 64, 64)
            .addComponent(labelActualDir)))
        .addContainerGap(327, Short.MAX_VALUE))
      .addGroup(layout.createSequentialGroup()
        .addGap(27, 27, 27)
        .addComponent(jComboBoxDirectorios, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(76, 76, 76))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(42, 42, 42)
        .addComponent(labelActualDir)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jComboBoxDirectorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addGap(18, 18, 18)
        .addComponent(jButtonDirectorios)
        .addGap(26, 26, 26))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jButtonDirectoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDirectoriosActionPerformed
        // TODO add your handling code here:
        Navegador n = new Navegador();

        Archivo raiz = ((Archivo)jComboBoxDirectorios.getSelectedItem());
        ArrayList<Archivo> archivos = n.directorios(raiz.getPath());
        labelActualDir.setText(raiz.getPath());
        jComboBoxDirectorios.removeAllItems();
        Archivo padre = n.crearArchivo(raiz.getParentPath());
        padre.setNombre("..");
        jComboBoxDirectorios.addItem(padre);


        subdirectorios.setText("");
        if (!archivos.isEmpty()) {
            for (Archivo a : archivos) {
                if (a.isIsDirectorio()) {
                    jComboBoxDirectorios.addItem(a);
                }
                subdirectorios.append(a.toString() + "\n");
            }
        } else {
            subdirectorios.append("vacio");

        }

    }//GEN-LAST:event_jButtonDirectoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Directorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Directorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Directorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Directorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Directorios().setVisible(true);
            }
        });
    }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonDirectorios;
  private javax.swing.JComboBox jComboBoxDirectorios;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel labelActualDir;
  private javax.swing.JTextArea subdirectorios;
  // End of variables declaration//GEN-END:variables
}
