package hibernate.mapping;
// Generated 30-dic-2014 1:01:00 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ComisionesTotales generated by hbm2java
 */
public class ComisionesTotales  implements java.io.Serializable {


     private String login;
     private Usuarios usuarios;
     private long comisiones;
     private Date fechaComprobacion;

    public ComisionesTotales() {
    }

	
    public ComisionesTotales(Usuarios usuarios, long comisiones) {
        this.usuarios = usuarios;
        this.comisiones = comisiones;
    }
    public ComisionesTotales(Usuarios usuarios, long comisiones, Date fechaComprobacion) {
       this.usuarios = usuarios;
       this.comisiones = comisiones;
       this.fechaComprobacion = fechaComprobacion;
    }
   
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public long getComisiones() {
        return this.comisiones;
    }
    
    public void setComisiones(long comisiones) {
        this.comisiones = comisiones;
    }
    public Date getFechaComprobacion() {
        return this.fechaComprobacion;
    }
    
    public void setFechaComprobacion(Date fechaComprobacion) {
        this.fechaComprobacion = fechaComprobacion;
    }




}


