package hibernate.mapping;
// Generated 30-dic-2014 1:01:00 by Hibernate Tools 4.3.1



/**
 * DatosPersonales generated by hbm2java
 */
public class DatosPersonales  implements java.io.Serializable {


     private String login;
     private Usuarios usuarios;
     private String nombre;
     private String apellidos;
     private String email;

    public DatosPersonales() {
    }

	
    public DatosPersonales(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public DatosPersonales(Usuarios usuarios, String nombre, String apellidos, String email) {
       this.usuarios = usuarios;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.email = email;
    }
   
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


