package hibernate.mapping;
// Generated 30-dic-2014 1:01:00 by Hibernate Tools 4.3.1



/**
 * DatosDirecciones generated by hbm2java
 */
public class DatosDirecciones  implements java.io.Serializable {


     private String login;
     private Usuarios usuarios;
     private String calle;
     private String portal;
     private String codigoPostal;
     private String piso;
     private String puerta;

    public DatosDirecciones() {
    }

	
    public DatosDirecciones(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public DatosDirecciones(Usuarios usuarios, String calle, String portal, String codigoPostal, String piso, String puerta) {
       this.usuarios = usuarios;
       this.calle = calle;
       this.portal = portal;
       this.codigoPostal = codigoPostal;
       this.piso = piso;
       this.puerta = puerta;
    }
   
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getPortal() {
        return this.portal;
    }
    
    public void setPortal(String portal) {
        this.portal = portal;
    }
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public String getPiso() {
        return this.piso;
    }
    
    public void setPiso(String piso) {
        this.piso = piso;
    }
    public String getPuerta() {
        return this.puerta;
    }
    
    public void setPuerta(String puerta) {
        this.puerta = puerta;
    }




}


