package hibernate.mapping;
// Generated 30-dic-2014 1:01:00 by Hibernate Tools 4.3.1



/**
 * LineaPedido generated by hbm2java
 */
public class LineaPedido  implements java.io.Serializable {


     private Integer idLineaPedido;
     private Pedidos pedidos;
     private Productos productos;
     private int cantidad;
     private long precioLinea;

    public LineaPedido() {
    }

    public LineaPedido(Pedidos pedidos, Productos productos, int cantidad, long precioLinea) {
       this.pedidos = pedidos;
       this.productos = productos;
       this.cantidad = cantidad;
       this.precioLinea = precioLinea;
    }
   
    public Integer getIdLineaPedido() {
        return this.idLineaPedido;
    }
    
    public void setIdLineaPedido(Integer idLineaPedido) {
        this.idLineaPedido = idLineaPedido;
    }
    public Pedidos getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Pedidos pedidos) {
        this.pedidos = pedidos;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public long getPrecioLinea() {
        return this.precioLinea;
    }
    
    public void setPrecioLinea(long precioLinea) {
        this.precioLinea = precioLinea;
    }




}


