package hibernate.mapping;
// Generated 30-dic-2014 1:01:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedidos generated by hbm2java
 */
public class Pedidos  implements java.io.Serializable {


     private Integer idPedido;
     private Productos productos;
     private Usuarios usuariosByUsuario;
     private Usuarios usuariosByDistribuidora;
     private Usuarios usuariosByJefaGrupo;
     private long precioTotal;
     private Date fechaCompra;
     private Date fechaEnvio;
     private Set lineaPedidos = new HashSet(0);

    public Pedidos() {
    }

	
    public Pedidos(Productos productos, Usuarios usuariosByUsuario, Usuarios usuariosByDistribuidora, Usuarios usuariosByJefaGrupo, long precioTotal, Date fechaCompra, Date fechaEnvio) {
        this.productos = productos;
        this.usuariosByUsuario = usuariosByUsuario;
        this.usuariosByDistribuidora = usuariosByDistribuidora;
        this.usuariosByJefaGrupo = usuariosByJefaGrupo;
        this.precioTotal = precioTotal;
        this.fechaCompra = fechaCompra;
        this.fechaEnvio = fechaEnvio;
    }
    public Pedidos(Productos productos, Usuarios usuariosByUsuario, Usuarios usuariosByDistribuidora, Usuarios usuariosByJefaGrupo, long precioTotal, Date fechaCompra, Date fechaEnvio, Set lineaPedidos) {
       this.productos = productos;
       this.usuariosByUsuario = usuariosByUsuario;
       this.usuariosByDistribuidora = usuariosByDistribuidora;
       this.usuariosByJefaGrupo = usuariosByJefaGrupo;
       this.precioTotal = precioTotal;
       this.fechaCompra = fechaCompra;
       this.fechaEnvio = fechaEnvio;
       this.lineaPedidos = lineaPedidos;
    }
   
    public Integer getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(Integer idPedido) {
        this.idPedido = idPedido;
    }
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
    public Usuarios getUsuariosByUsuario() {
        return this.usuariosByUsuario;
    }
    
    public void setUsuariosByUsuario(Usuarios usuariosByUsuario) {
        this.usuariosByUsuario = usuariosByUsuario;
    }
    public Usuarios getUsuariosByDistribuidora() {
        return this.usuariosByDistribuidora;
    }
    
    public void setUsuariosByDistribuidora(Usuarios usuariosByDistribuidora) {
        this.usuariosByDistribuidora = usuariosByDistribuidora;
    }
    public Usuarios getUsuariosByJefaGrupo() {
        return this.usuariosByJefaGrupo;
    }
    
    public void setUsuariosByJefaGrupo(Usuarios usuariosByJefaGrupo) {
        this.usuariosByJefaGrupo = usuariosByJefaGrupo;
    }
    public long getPrecioTotal() {
        return this.precioTotal;
    }
    
    public void setPrecioTotal(long precioTotal) {
        this.precioTotal = precioTotal;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public Date getFechaEnvio() {
        return this.fechaEnvio;
    }
    
    public void setFechaEnvio(Date fechaEnvio) {
        this.fechaEnvio = fechaEnvio;
    }
    public Set getLineaPedidos() {
        return this.lineaPedidos;
    }
    
    public void setLineaPedidos(Set lineaPedidos) {
        this.lineaPedidos = lineaPedidos;
    }




}


