package hibernate.mapping;
// Generated 30-dic-2014 1:01:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private String codigo;
     private String nombre;
     private double precio;
     private Date fechaFin;
     private Set pedidoses = new HashSet(0);
     private Set lineaPedidos = new HashSet(0);

    public Productos() {
    }

	
    public Productos(String codigo, String nombre, double precio) {
        this.codigo = codigo;
        this.nombre = nombre;
        this.precio = precio;
    }
    public Productos(String codigo, String nombre, double precio, Date fechaFin, Set pedidoses, Set lineaPedidos) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.precio = precio;
       this.fechaFin = fechaFin;
       this.pedidoses = pedidoses;
       this.lineaPedidos = lineaPedidos;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public Set getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set pedidoses) {
        this.pedidoses = pedidoses;
    }
    public Set getLineaPedidos() {
        return this.lineaPedidos;
    }
    
    public void setLineaPedidos(Set lineaPedidos) {
        this.lineaPedidos = lineaPedidos;
    }




}


