package hibernate.mapping;
// Generated 30-dic-2014 1:01:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private String login;
     private TiposUsuarios tiposUsuarios;
     private String password;
     private DatosPersonales datosPersonales;
     private Set pedidosesForUsuario = new HashSet(0);
     private Set pedidosesForDistribuidora = new HashSet(0);
     private ComisionesTotales comisionesTotales;
     private DatosDirecciones datosDirecciones;
     private Set pedidosesForJefaGrupo = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(String login, TiposUsuarios tiposUsuarios, String password) {
        this.login = login;
        this.tiposUsuarios = tiposUsuarios;
        this.password = password;
    }
    public Usuarios(String login, TiposUsuarios tiposUsuarios, String password, DatosPersonales datosPersonales, Set pedidosesForUsuario, Set pedidosesForDistribuidora, ComisionesTotales comisionesTotales,DatosDirecciones datosDirecciones, Set pedidosesForJefaGrupo) {
       this.login = login;
       this.tiposUsuarios = tiposUsuarios;
       this.password = password;
       this.datosPersonales = datosPersonales;
       this.pedidosesForUsuario = pedidosesForUsuario;
       this.pedidosesForDistribuidora = pedidosesForDistribuidora;
       this.comisionesTotales = comisionesTotales;
       this.datosDirecciones = datosDirecciones;
       this.pedidosesForJefaGrupo = pedidosesForJefaGrupo;
    }
   
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public TiposUsuarios getTiposUsuarios() {
        return this.tiposUsuarios;
    }
    
    public void setTiposUsuarios(TiposUsuarios tiposUsuarios) {
        this.tiposUsuarios = tiposUsuarios;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public DatosPersonales getDatosPersonales() {
        return this.datosPersonales;
    }
    
    public void setDatosPersonales(DatosPersonales datosPersonales) {
        this.datosPersonales = datosPersonales;
    }
    public Set getPedidosesForUsuario() {
        return this.pedidosesForUsuario;
    }
    
    public void setPedidosesForUsuario(Set pedidosesForUsuario) {
        this.pedidosesForUsuario = pedidosesForUsuario;
    }
    public Set getPedidosesForDistribuidora() {
        return this.pedidosesForDistribuidora;
    }
    
    public void setPedidosesForDistribuidora(Set pedidosesForDistribuidora) {
        this.pedidosesForDistribuidora = pedidosesForDistribuidora;
    }
    public ComisionesTotales getComisionesTotales() {
        return this.comisionesTotales;
    }
    
    public void setComisionesTotales(ComisionesTotales comisionesTotales) {
        this.comisionesTotales = comisionesTotales;
    }
    public DatosDirecciones getDatosDirecciones() {
        return this.datosDirecciones;
    }
    
    public void setDatosDirecciones(DatosDirecciones datosDirecciones) {
        this.datosDirecciones = datosDirecciones;
    }
    public Set getPedidosesForJefaGrupo() {
        return this.pedidosesForJefaGrupo;
    }
    
    public void setPedidosesForJefaGrupo(Set pedidosesForJefaGrupo) {
        this.pedidosesForJefaGrupo = pedidosesForJefaGrupo;
    }




}


