package quevedo.hibernate;
// Generated 22-feb-2015 13:48:13 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ComisionesTotales generated by hbm2java
 */
public class ComisionesTotales  implements java.io.Serializable {


     private String login;
     private long comisiones;
     private Date fechaComprobacion;

    public ComisionesTotales() {
    }

	
    public ComisionesTotales(String login, long comisiones) {
        this.login = login;
        this.comisiones = comisiones;
    }
    public ComisionesTotales(String login, long comisiones, Date fechaComprobacion) {
       this.login = login;
       this.comisiones = comisiones;
       this.fechaComprobacion = fechaComprobacion;
    }
   
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public long getComisiones() {
        return this.comisiones;
    }
    
    public void setComisiones(long comisiones) {
        this.comisiones = comisiones;
    }
    public Date getFechaComprobacion() {
        return this.fechaComprobacion;
    }
    
    public void setFechaComprobacion(Date fechaComprobacion) {
        this.fechaComprobacion = fechaComprobacion;
    }




}


