package quevedo.hibernate;
// Generated 22-feb-2015 13:48:13 by Hibernate Tools 4.3.1



/**
 * DatosPersonales generated by hbm2java
 */
public class DatosPersonales  implements java.io.Serializable {


     private String login;
     private String nombre;
     private String apellidos;
     private String email;

    public DatosPersonales() {
    }

	
    public DatosPersonales(String login) {
        this.login = login;
    }
    public DatosPersonales(String login, String nombre, String apellidos, String email) {
       this.login = login;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.email = email;
    }
   
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


