package quevedo.hibernate;
// Generated 22-feb-2015 13:48:13 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pedidos generated by hbm2java
 */
public class Pedidos  implements java.io.Serializable {


     private Integer idPedido;
     private String codigoProducto;
     private String usuario;
     private String distribuidora;
     private String jefaGrupo;
     private long precioTotal;
     private Date fechaCompra;
     private Date fechaEnvio;

    public Pedidos() {
    }

    public Pedidos(String codigoProducto, String usuario, String distribuidora, String jefaGrupo, long precioTotal, Date fechaCompra, Date fechaEnvio) {
       this.codigoProducto = codigoProducto;
       this.usuario = usuario;
       this.distribuidora = distribuidora;
       this.jefaGrupo = jefaGrupo;
       this.precioTotal = precioTotal;
       this.fechaCompra = fechaCompra;
       this.fechaEnvio = fechaEnvio;
    }
   
    public Integer getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(Integer idPedido) {
        this.idPedido = idPedido;
    }
    public String getCodigoProducto() {
        return this.codigoProducto;
    }
    
    public void setCodigoProducto(String codigoProducto) {
        this.codigoProducto = codigoProducto;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getDistribuidora() {
        return this.distribuidora;
    }
    
    public void setDistribuidora(String distribuidora) {
        this.distribuidora = distribuidora;
    }
    public String getJefaGrupo() {
        return this.jefaGrupo;
    }
    
    public void setJefaGrupo(String jefaGrupo) {
        this.jefaGrupo = jefaGrupo;
    }
    public long getPrecioTotal() {
        return this.precioTotal;
    }
    
    public void setPrecioTotal(long precioTotal) {
        this.precioTotal = precioTotal;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public Date getFechaEnvio() {
        return this.fechaEnvio;
    }
    
    public void setFechaEnvio(Date fechaEnvio) {
        this.fechaEnvio = fechaEnvio;
    }




}


