package quevedo.hibernate;
// Generated 22-feb-2015 13:48:13 by Hibernate Tools 4.3.1



/**
 * TiposComision generated by hbm2java
 */
public class TiposComision  implements java.io.Serializable {


     private int idTipoComision;
     private int idTipoUsuario;
     private long porcentaje;

    public TiposComision() {
    }

    public TiposComision(int idTipoComision, int idTipoUsuario, long porcentaje) {
       this.idTipoComision = idTipoComision;
       this.idTipoUsuario = idTipoUsuario;
       this.porcentaje = porcentaje;
    }
   
    public int getIdTipoComision() {
        return this.idTipoComision;
    }
    
    public void setIdTipoComision(int idTipoComision) {
        this.idTipoComision = idTipoComision;
    }
    public int getIdTipoUsuario() {
        return this.idTipoUsuario;
    }
    
    public void setIdTipoUsuario(int idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }
    public long getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(long porcentaje) {
        this.porcentaje = porcentaje;
    }




}


