package quevedo.hibernate;
// Generated 22-feb-2015 13:48:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TiposUsuarios generated by hbm2java
 */
public class TiposUsuarios  implements java.io.Serializable {


     private int idTipoUsuario;
     private String descripcion;
     private Set usuarioses = new HashSet(0);

    public TiposUsuarios() {
    }

	
    public TiposUsuarios(int idTipoUsuario, String descripcion) {
        this.idTipoUsuario = idTipoUsuario;
        this.descripcion = descripcion;
    }
    public TiposUsuarios(int idTipoUsuario, String descripcion, Set usuarioses) {
       this.idTipoUsuario = idTipoUsuario;
       this.descripcion = descripcion;
       this.usuarioses = usuarioses;
    }
   
    public int getIdTipoUsuario() {
        return this.idTipoUsuario;
    }
    
    public void setIdTipoUsuario(int idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


