package quevedo.hibernate;
// Generated 22-feb-2015 13:48:13 by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private String login;
     private TiposUsuarios tiposUsuarios;
     private String password;

    public Usuarios() {
    }

    public Usuarios(String login, TiposUsuarios tiposUsuarios, String password) {
       this.login = login;
       this.tiposUsuarios = tiposUsuarios;
       this.password = password;
    }
   
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public TiposUsuarios getTiposUsuarios() {
        return this.tiposUsuarios;
    }
    
    public void setTiposUsuarios(TiposUsuarios tiposUsuarios) {
        this.tiposUsuarios = tiposUsuarios;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


