/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package basedatos;

import datos.Compra;
import datos.Persona;
import factoria.TiposSave;
import factoria.SaveFactory;
import factoria.Saveable;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import negocio.Comprobacion;
import util.Constantes;

/**
 *
 * @author profesor
 */
public class FramePersonas extends javax.swing.JFrame {

    /**
     * Creates new form FramePersonas
     */
    Comprobacion c = new Comprobacion();
    Saveable save = null;
    private String rutaBD = null;
    HashMap<Integer, Persona> personas = new HashMap<>();

    //<editor-fold defaultstate="collapsed" desc="modelo de la tabla persona">
    public DefaultTableModel crearModeloPersonas() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("NOMBRE");
        model.addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                if (e.getType() == TableModelEvent.UPDATE) {
                    String id = jTablePersonas.getValueAt(e.getFirstRow(), Constantes.COLUMN_PERSONA_ID).toString();
                    Persona p = personas.get(Integer.parseInt(id));
                    // Se podria hacer sin if pq solo hay una columna
                    if (e.getColumn() == Constantes.COLUMN_PERSONA_NOMBRE) {
                        p.setNombre(jTablePersonas.getValueAt(e.getFirstRow(), Constantes.COLUMN_PERSONA_NOMBRE).toString());
                    }
                }
            }
        });

        return model;
    }

    public void addPersonaaTabla(Persona p) {
        DefaultTableModel model = ((DefaultTableModel) jTablePersonas.getModel());
        model.addRow(new Object[]{p.getId(), p.getNombre()});
    }

    //</editor-fold>
    public void vaciarTabla(JTable tabla) {
        for (int i = 0; i < tabla.getRowCount(); i++) {
            ((DefaultTableModel) tabla.getModel()).removeRow(i);
        }
    }

    public FramePersonas() {
        initComponents();
        leerProperties();
        this.setLocationRelativeTo(null);
        // OJO tiene que tener un valor al arrancar.
        cargarFactoria();
        jTablePersonas.setModel(crearModeloPersonas());
    }

    //<editor-fold defaultstate="collapsed" desc="inicializacion">
    private void leerProperties() {
        FileReader file = null;
        Properties p = null;
        try {
            p = new Properties();
            file = new FileReader(Constantes.FICHERO_PROPERTIES);
            p.load(file);
            rutaBD = p.getProperty(Constantes.RUTABD_PROPERTY);
        } catch (FileNotFoundException e) {
            System.out.println("FileNotFound");
        } catch (IOException e) {
            System.out.println("IOEXCeption");
        } finally {
            if (file != null) {
                try {
                    file.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            } else {
            }
        }
    }

    private void cargarFactoria() {
        SaveFactory fac = new SaveFactory();
        if (jComboBoxTipoFactoria.getSelectedItem().equals("JaxB")) {
            save = fac.build(TiposSave.JAXB);
        } else {
            save = fac.build(TiposSave.XSTREAM);
        }
    }
    //</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogCompras = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCompras = new javax.swing.JTable();
        jButtonCrearCompras = new javax.swing.JButton();
        jbuttonGuardarCompras = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonBorrarCompras = new javax.swing.JButton();
        jButonCancelarCompras = new javax.swing.JButton();
        jTextCantidad = new javax.swing.JTextField();
        jTextConcepto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePersonas = new javax.swing.JTable();
        jTextId = new javax.swing.JTextField();
        jTextNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonCrearPersona = new javax.swing.JButton();
        jButtonComprasDePersona = new javax.swing.JButton();
        jButtonBorrarPersona = new javax.swing.JButton();
        jButtonCargarPersona = new javax.swing.JButton();
        jButtonGuardarPersona = new javax.swing.JButton();
        jComboBoxTipoFactoria = new javax.swing.JComboBox();

        jDialogCompras.setMinimumSize(new java.awt.Dimension(400, 400));
        jDialogCompras.setModal(true);
        jDialogCompras.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jDialogComprasWindowClosing(evt);
            }
        });

        jTableCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableCompras);

        jButtonCrearCompras.setText("Crear");
        jButtonCrearCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearComprasActionPerformed(evt);
            }
        });

        jbuttonGuardarCompras.setText("Guardar");
        jbuttonGuardarCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarComprasActionPerformed(evt);
            }
        });

        jLabel3.setText("Cliente");

        jButtonBorrarCompras.setText("Borrar");
        jButtonBorrarCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarComprasActionPerformed(evt);
            }
        });

        jButonCancelarCompras.setText("Cancelar");
        jButonCancelarCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarComprasActionPerformed(evt);
            }
        });

        jLabel4.setText("Cantidad: ");

        jLabel5.setText("Concepto:");

        javax.swing.GroupLayout jDialogComprasLayout = new javax.swing.GroupLayout(jDialogCompras.getContentPane());
        jDialogCompras.getContentPane().setLayout(jDialogComprasLayout);
        jDialogComprasLayout.setHorizontalGroup(
            jDialogComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogComprasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogComprasLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextCantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextConcepto, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogComprasLayout.createSequentialGroup()
                        .addComponent(jButtonBorrarCompras, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCrearCompras, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButonCancelarCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 90, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbuttonGuardarCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 90, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jDialogComprasLayout.setVerticalGroup(
            jDialogComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogComprasLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonBorrarCompras)
                        .addComponent(jButtonCrearCompras)
                        .addComponent(jbuttonGuardarCompras))
                    .addComponent(jButonCancelarCompras))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTablePersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTablePersonas);

        jLabel1.setText("Id");

        jLabel2.setText("Nombre");

        jButtonCrearPersona.setText("Crear");
        jButtonCrearPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearPersonaActionPerformed(evt);
            }
        });

        jButtonComprasDePersona.setLabel("Compras");
        jButtonComprasDePersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprasActionPerformed(evt);
            }
        });

        jButtonBorrarPersona.setText("Borrar");
        jButtonBorrarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarPersonaActionPerformed(evt);
            }
        });

        jButtonCargarPersona.setText("Cargar");
        jButtonCargarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarPersonaActionPerformed(evt);
            }
        });

        jButtonGuardarPersona.setText("Guardar");
        jButtonGuardarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarPersonaActionPerformed(evt);
            }
        });

        jComboBoxTipoFactoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Xstream", "JaxB" }));
        jComboBoxTipoFactoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoFactoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextId, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCrearPersona, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonComprasDePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 91, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBorrarPersona, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGuardarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 81, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCargarPersona, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                        .addGap(6, 6, 6)))
                .addContainerGap())
            .addComponent(jComboBoxTipoFactoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(jComboBoxTipoFactoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCrearPersona)
                    .addComponent(jButtonComprasDePersona)
                    .addComponent(jButtonBorrarPersona)
                    .addComponent(jButtonGuardarPersona)
                    .addComponent(jButtonCargarPersona))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private HashMap<Integer, Persona> deTablaAHashMap() {
        Persona p = null;
        // se limpia el hash.
        personas.clear();
        for (int i = 0; i < jTablePersonas.getRowCount(); i++) {
            try {
                p = new Persona(
                        Integer.parseInt(jTablePersonas.getModel().getValueAt(i, Constantes.COLUMN_PERSONA_ID).toString()),
                        (String) jTablePersonas.getModel().getValueAt(i, Constantes.COLUMN_PERSONA_NOMBRE));
                personas.put(p.getId(), p);
            } catch (NumberFormatException numberFormatException) {
                JOptionPane.showMessageDialog(this, "IDs no validos eliminados");
            }
        }
        return personas;
    }

    private void deHashMapATabla(HashMap<Integer, Persona> personas) {
        vaciarTabla(jTablePersonas);
        for (Persona p : personas.values()) {
            ((DefaultTableModel) jTablePersonas.getModel())
                    .addRow(new Object[]{p.getId(), p.getNombre()});
        }
    }

    private void crearYAnadirPersona(HashMap<Integer, Persona> hashp, Persona p) {
        hashp.put(p.getId(), p);
        this.addPersonaaTabla(p);
    }

    private ArrayList<Compra> deTablaAArray() {
        ArrayList<Compra> compras = new ArrayList<>();
        Compra c = null;
        for (int i = 0; i < jTableCompras.getRowCount(); i++) {
            try {
                c = new Compra(
                        Integer.parseInt(jTableCompras.getModel().getValueAt(i, Constantes.COLUMN_COMPRA_CANTIDAD).toString()),
                        (String) jTableCompras.getModel().getValueAt(i, Constantes.COLUMN_COMPRA_CONCEPTO));

                compras.add(c);
            } catch (NumberFormatException numberFormatException) {
                JOptionPane.showMessageDialog(this, "Cantidades no validas eliminadas");
            }
        }
        return compras;
    }

    private void deArrayATabla(ArrayList<Compra> compras) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("CANTIDAD");
        model.addColumn("CONCEPTO");
        jTableCompras.setModel(model);
        for (Compra compra : compras) {
            model.addRow(new Object[]{compra.getCantidad(), compra.getConcepto()});
        }
    }

    private void crearYAnadirCompra(ArrayList<Compra> compras, Compra c) {
        compras.add(c);
        DefaultTableModel model = ((DefaultTableModel) jTableCompras.getModel());
        model.addRow(new Object[]{c.getCantidad(), c.getConcepto()});
    }

//<editor-fold defaultstate="collapsed" desc="eventos botones persona">
    private void jButtonCrearPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearPersonaActionPerformed
        if (jTextId.getText().equals("") || jTextNombre.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No has introducido datos para crear la persona");
        } else {

            try {
                int enteroTextId = Integer.parseInt(jTextId.getText());
                if (!personas.containsKey(enteroTextId)) {
                    crearYAnadirPersona(personas, new Persona(Integer.parseInt(jTextId.getText()), jTextNombre.getText()));

                    JOptionPane.showMessageDialog(this, "Creado");
                } else {
                    JOptionPane.showMessageDialog(this, "Ese ID ya existe");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "ID no valido");
            }
        }

    }//GEN-LAST:event_jButtonCrearPersonaActionPerformed

    private void jButtonGuardarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarPersonaActionPerformed
        if (comprobarID() == true) {
            //personas = deTablaAHashMap();
            save.personasToXML(personas, Constantes.NOMBREFICHERO_PROPERTY);
            JOptionPane.showMessageDialog(this, "Guardado");
        } else {
            JOptionPane.showMessageDialog(this, "No se puede guardar hasta que no haya IDs sin repetir");
        }


    }//GEN-LAST:event_jButtonGuardarPersonaActionPerformed
    private void jButtonCargarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarPersonaActionPerformed

        try {
            deHashMapATabla(save.personasFromXML(Constantes.NOMBREFICHERO_PROPERTY));
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jButtonCargarPersonaActionPerformed

    private void jButtonComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprasActionPerformed
        try {
            jDialogCompras.setTitle(personaSeleccionada().getNombre());
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("CANTIDAD");
            model.addColumn("CONCEPTO");
            jTableCompras.setModel(model);
            HashMap<Integer, Persona> personas = deTablaAHashMap();
            int fila = jTablePersonas.getSelectedRow();
            if (fila >= 0) {
                jLabel3.setText("Compras de: " + personaSeleccionada().getNombre());
                File f = new File(personaSeleccionada().getId() + ".xml");
                if (f.exists()) {
                    ArrayList<Compra> compras = save.comprasFromXML(personaSeleccionada().getId() + ".xml");
                    deArrayATabla(compras);
                }
                jDialogCompras.setLocationRelativeTo(null);
                jDialogCompras.setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Selecciona una persona");
        }
    }//GEN-LAST:event_jButtonComprasActionPerformed
    private void jButtonBorrarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarPersonaActionPerformed
        DefaultTableModel model = ((DefaultTableModel) jTablePersonas.getModel());
        try {
            File c = new File(jTablePersonas.getModel().getValueAt(jTablePersonas.getSelectedRow(), Constantes.COLUMN_PERSONA_ID).toString() + ".dat");
            c.delete();
            model.removeRow(jTablePersonas.getSelectedRow());
            HashMap<Integer, Persona> personas = deTablaAHashMap();
            save.personasToXML(personas, Constantes.NOMBREFICHERO_PROPERTY);
            JOptionPane.showMessageDialog(this, "Borrado");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Selecciona una persona");
        }
    }//GEN-LAST:event_jButtonBorrarPersonaActionPerformed
//</editor-fold>

//<editor-fold defaultstate="collapsed" desc="eventos botones compras">  
    private void jButtonCancelarComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarComprasActionPerformed
        jDialogCompras.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarComprasActionPerformed

    private void jButtonBorrarComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarComprasActionPerformed
        DefaultTableModel model = ((DefaultTableModel) jTableCompras.getModel());
        try {
            model.removeRow(jTableCompras.getSelectedRow());
            ArrayList<Compra> compras = deTablaAArray();
            save.comprasToXML(compras, personaSeleccionada().getId() + ".xml");
            JOptionPane.showMessageDialog(jDialogCompras, "Borrado");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Selecciona una compra");
        }
    }//GEN-LAST:event_jButtonBorrarComprasActionPerformed

    private void jButtonGuardarComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarComprasActionPerformed
        ArrayList<Compra> compras = deTablaAArray();
        save.comprasToXML(compras, personaSeleccionada().getId() + ".xml");
        JOptionPane.showMessageDialog(jDialogCompras, "Guardado");
        //LLamamos otra vez al boton para recargar la tabla
        jButtonComprasActionPerformed(null);
    }//GEN-LAST:event_jButtonGuardarComprasActionPerformed

    private void jButtonCrearComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearComprasActionPerformed
        if (jTextCantidad.getText().equals("") || jTextConcepto.getText().equals("")) {
            JOptionPane.showMessageDialog(jDialogCompras, "No has introducido datos para crear la compra");
        } else {

            try {
                int enteroTextCantidad = Integer.parseInt(jTextCantidad.getText());
                ArrayList<Compra> compras = deTablaAArray();
                crearYAnadirCompra(compras, new Compra(Integer.parseInt(jTextCantidad.getText()), jTextConcepto.getText()));
                save.comprasToXML(compras, personaSeleccionada().getId() + ".xml");
                JOptionPane.showMessageDialog(jDialogCompras, "Creado");
            } catch (NumberFormatException numberFormatException) {
                JOptionPane.showMessageDialog(jDialogCompras, "Cantidad no valida");
            }

        }
    }//GEN-LAST:event_jButtonCrearComprasActionPerformed

    private void jDialogComprasWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogComprasWindowClosing
        int seleccion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que quieres cerrar sin darle a guardar?");
        if (seleccion == JOptionPane.YES_OPTION) {
            jDialogCompras.setVisible(false);
        } else {
            jDialogCompras.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        }

    }//GEN-LAST:event_jDialogComprasWindowClosing
//</editor-fold>

    private void jComboBoxTipoFactoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoFactoriaActionPerformed
        cargarFactoria();
    }//GEN-LAST:event_jComboBoxTipoFactoriaActionPerformed

    public Persona personaSeleccionada() {
        int fila = jTablePersonas.getSelectedRow();
        Persona p = null;
        if (fila >= 0) {
            p = personas.get(jTablePersonas.getModel().getValueAt(fila, Constantes.COLUMN_PERSONA_ID).toString());
        }
        return p;
    }

    // no es necesario.
    public boolean comprobarID() {
        int contador = 0;
        boolean solucion = true;
        if (jTablePersonas.getSelectedRow() != -1) {
            for (int i = 0; i < jTablePersonas.getRowCount(); i++) {
                String existe = jTablePersonas.getModel().getValueAt(i, Constantes.COLUMN_PERSONA_ID).toString();
                String actual = (String) jTablePersonas.getValueAt(jTablePersonas.getSelectedRow(), Constantes.COLUMN_PERSONA_ID);
                if (existe.equals(actual)) {
                    contador++;
                }
            }
            if (contador > 1) {
                solucion = false;
            }
        }
        return solucion;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePersonas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButonCancelarCompras;
    private javax.swing.JButton jButtonBorrarCompras;
    private javax.swing.JButton jButtonBorrarPersona;
    private javax.swing.JButton jButtonCargarPersona;
    private javax.swing.JButton jButtonComprasDePersona;
    private javax.swing.JButton jButtonCrearCompras;
    private javax.swing.JButton jButtonCrearPersona;
    private javax.swing.JButton jButtonGuardarPersona;
    private javax.swing.JComboBox jComboBoxTipoFactoria;
    private javax.swing.JDialog jDialogCompras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCompras;
    private javax.swing.JTable jTablePersonas;
    private javax.swing.JTextField jTextCantidad;
    private javax.swing.JTextField jTextConcepto;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JButton jbuttonGuardarCompras;
    // End of variables declaration//GEN-END:variables
}
